class Excuse < CampfireBot::Plugin
  
  on_command 'excuse', :excuse
  
  def excuse(msg)
    
    excuses = %w(clock_speed
    solar_flares
    electromagnetic_radiation_from_satellite_debris
    static_from_nylon_underwear
    static_from_plastic_slide_rules
    global_warming
    poor_power_conditioning
    static_buildup
    doppler_effect
    hardware_stress_fractures
    magnetic_interference_from_money/credit_cards
    dry_joints_on_cable_plug
    we're_waiting_for_[the_phone_company]_to_fix_that_line
    sounds_like_a_Windows_problem,_try_calling_Microsoft_support
    temporary_routing_anomaly
    somebody_was_calculating_pi_on_the_server
    fat_electrons_in_the_lines
    excess_surge_protection
    floating_point_processor_overflow
    divide-by-zero_error
    POSIX_compliance_problem
    monitor_resolution_too_high
    improperly_oriented_keyboard
    network_packets_travelling_uphill_(use_a_carrier_pigeon)
    Decreasing_electron_flux
    first_Saturday_after_first_full_moon_in_Winter
    radiosity_depletion
    CPU_radiator_broken
    It_works_the_way_the_Wang_did,_what's_the_problem
    positron_router_malfunction
    cellular_telephone_interference
    techtonic_stress
    piezo-electric_interference
    (l)user_error
    working_as_designed
    dynamic_software_linking_table_corrupted
    heavy_gravity_fluctuation,_move_computer_to_floor_rapidly
    secretary_plugged_hairdryer_into_UPS
    terrorist_activities
    not_enough_memory,_go_get_system_upgrade
    interrupt_configuration_error
    spaghetti_cable_cause_packet_failure
    boss_forgot_system_password
    bank_holiday_-_system_operating_credits__not_recharged
    virus_attack,_luser_responsible
    waste_water_tank_overflowed_onto_computer
    Complete_Transient_Lockout
    bad_ether_in_the_cables
    Bogon_emissions
    Change_in_Earth's_rotational_speed
    Cosmic_ray_particles_crashed_through_the_hard_disk_platter
    Smell_from_unhygienic_janitorial_staff_wrecked_the_tape_heads
    Little_hamster_in_running_wheel_had_coronary;_waiting_for_replacement_to_be_Fedexed_from_Wyoming
    Evil_dogs_hypnotised_the_night_shift
    Plumber_mistook_routing_panel_for_decorative_wall_fixture
    Electricians_made_popcorn_in_the_power_supply
    Groundskeepers_stole_the_root_password
    high_pressure_system_failure
    failed_trials,_system_needs_redesigned
    system_has_been_recalled
    not_approved_by_the_FCC
    need_to_wrap_system_in_aluminum_foil_to_fix_problem
    not_properly_grounded,_please_bury_computer
    CPU_needs_recalibration
    system_needs_to_be_rebooted
    bit_bucket_overflow
    descramble_code_needed_from_software_company
    only_available_on_a_need_to_know_basis
    knot_in_cables_caused_data_stream_to_become_twisted_and_kinked
    nesting_roaches_shorted_out_the_ether_cable
    The_file_system_is_full_of_it
    Satan_did_it
    Daemons_did_it
    You're_out_of_memory
    There_isn't_any_problem
    Unoptimized_hard_drive
    Typo_in_the_code
    Yes,_yes,_its_called_a_design_limitation
    Look,_buddy:__Windows_3.1_IS_A_General_Protection_Fault.
    That's_a_great_computer_you_have_there;_have_you_considered_how_it_would_work_as_a_BSD_machine?
    Please_excuse_me,_I_have_to_circuit_an_AC_line_through_my_head_to_get_this_database_working.
    Yeah,_yo_mama_dresses_you_funny_and_you_need_a_mouse_to_delete_files.
    Support_staff_hung_over,_send_aspirin_and_come_back_LATER.
    Someone_is_standing_on_the_ethernet_cable,_causing_a_kink_in_the_cable
    Windows_95_undocumented_"feature"
    Runt_packets
    Password_is_too_complex_to_decrypt
    Boss'_kid_fucked_up_the_machine
    Electromagnetic_energy_loss
    Budget_cuts
    Mouse_chewed_through_power_cable
    Stale_file_handle_(next_time_use_Tupperware(tm)!)
    Feature_not_yet_implemented
    Internet_outage
    Pentium_FDIV_bug
    Vendor_no_longer_supports_the_product
    Small_animal_kamikaze_attack_on_power_supplies
    The_vendor_put_the_bug_there.
    SIMM_crosstalk.
    IRQ_dropout
    Collapsed_Backbone
    Power_company_testing_new_voltage_spike_(creation)_equipment
    operators_on_strike_due_to_broken_coffee_machine
    backup_tape_overwritten_with_copy_of_system_manager's_favourite_CD
    UPS_interrupted_the_server's_power
    The_electrician_didn't_know_what_the_yellow_cable_was_so_he_yanked_the_ethernet_out.
    The_keyboard_isn't_plugged_in
    The_air_conditioning_water_supply_pipe_ruptured_over_the_machine_room
    The_electricity_substation_in_the_car_park_blew_up.
    The_rolling_stones_concert_down_the_road_caused_a_brown_out
    The_salesman_drove_over_the_CPU_board.
    The_monitor_is_plugged_into_the_serial_port
    Root_nameservers_are_out_of_sync
    electro-magnetic_pulses_from_French_above_ground_nuke_testing.
    your_keyboard's_space_bar_is_generating_spurious_keycodes.
    the_real_ttys_became_pseudo_ttys_and_vice-versa.
    the_printer_thinks_its_a_router.
    the_router_thinks_its_a_printer.
    evil_hackers_from_Serbia.
    we_just_switched_to_FDDI.
    halon_system_went_off_and_killed_the_operators.
    because_Bill_Gates_is_a_Jehovah's_witness_and_so_nothing_can_work_on_St._Swithin's_day.
    user_to_computer_ratio_too_high.
    user_to_computer_ration_too_low.
    we_just_switched_to_Sprint.
    it_has_Intel_Inside
    Sticky_bits_on_disk.
    Power_Company_having_EMP_problems_with_their_reactor
    The_ring_needs_another_token
    new_management
    telnet:_Unable_to_connect_to_remote_host:_Connection_refused
    SCSI_Chain_overterminated
    It's_not_plugged_in.
    because_of_network_lag_due_to_too_many_people_playing_deathmatch
    You_put_the_disk_in_upside_down.
    Daemons_loose_in_system.
    User_was_distributing_pornography_on_server;_system_seized_by_FBI.
    BNC_(brain_not_connected)
    UBNC_(user_brain_not_connected)
    LBNC_(luser_brain_not_connected)
    disks_spinning_backwards_-_toggle_the_hemisphere_jumper.
    new_guy_cross-connected_phone_lines_with_ac_power_bus.
    had_to_use_hammer_to_free_stuck_disk_drive_heads.
    Too_few_computrons_available.
    Flat_tire_on_station_wagon_with_tapes.__("Never_underestimate_the_bandwidth_of_a_station_wagon_full_of_tapes_hurling_down_the_highway"_Andrew_S._Tannenbaum)_
    Communications_satellite_used_by_the_military_for_star_wars.
    Party-bug_in_the_Aloha_protocol.
    Insert_coin_for_new_game
    Dew_on_the_telephone_lines.
    Arcserve_crashed_the_server_again.
    Some_one_needed_the_powerstrip,_so_they_pulled_the_switch_plug.
    My_pony-tail_hit_the_on/off_switch_on_the_power_strip.
    Big_to_little_endian_conversion_error
    You_can_tune_a_file_system,_but_you_can't_tune_a_fish_(from_most_tunefs_man_pages)
    Dumb_terminal
    Zombie_processes_haunting_the_computer
    Incorrect_time_synchronization
    Defunct_processes
    Stubborn_processes
    non-redundant_fan_failure_
    monitor_VLF_leakage
    bugs_in_the_RAID
    no_"any"_key_on_keyboard
    root_rot
    Backbone_Scoliosis
    /pub/lunch
    excessive_collisions_&_not_enough_packet_ambulances
    le0:_no_carrier:_transceiver_cable_problem?
    broadcast_packets_on_wrong_frequency
    popper_unable_to_process_jumbo_kernel
    NOTICE:_alloc:_/dev/null:_filesystem_full
    pseudo-user_on_a_pseudo-terminal
    Recursive_traversal_of_loopback_mount_points
    Backbone_adjustment
    OS_swapped_to_disk
    vapors_from_evaporating_sticky-note_adhesives
    sticktion
    short_leg_on_process_table
    multicasts_on_broken_packets
    ether_leak
    Atilla_the_Hub
    endothermal_recalibration
    filesystem_not_big_enough_for_Jumbo_Kernel_Patch
    loop_found_in_loop_in_redundant_loopback
    system_consumed_all_the_paper_for_paging
    permission_denied
    Reformatting_Page._Wait...
    ..disk_or_the_processor_is_on_fire.
    SCSI's_too_wide.
    Proprietary_Information.
    Just_type_'mv_*_/dev/null'.
    runaway_cat_on_system.
    Did_you_pay_the_new_Support_Fee?
    We_only_support_a_1200_bps_connection.
    We_only_support_a_28000_bps_connection.
    Me_no_internet,_only_janitor,_me_just_wax_floors.
    I'm_sorry_a_pentium_won't_do,_you_need_an_SGI_to_connect_with_us.
    Post-it_Note_Sludge_leaked_into_the_monitor.
    the_curls_in_your_keyboard_cord_are_losing_electricity.
    The_monitor_needs_another_box_of_pixels.
    RPC_PMAP_FAILURE
    kernel_panic:_write-only-memory_(/dev/wom0)_capacity_exceeded.
    Write-only-memory_subsystem_too_slow_for_this_machine._Contact_your_local_dealer.
    Just_pick_up_the_phone_and_give_modem_connect_sounds._"Well_you_said_we_should_get_more_lines_so_we_don't_have_voice_lines."
    Quantum_dynamics_are_affecting_the_transistors
    Police_are_examining_all_internet_packets_in_the_search_for_a_narco-net-trafficker
    We_are_currently_trying_a_new_concept_of_using_a_live_mouse.__Unfortunately,_one_has_yet_to_survive_being_hooked_up_to_the_computer.....please_bear_with_us.
    Your_mail_is_being_routed_through_Germany_..._and_they're_censoring_us.
    Only_people_with_names_beginning_with_'A'_are_getting_mail_this_week_(a_la_Microsoft)
    We_didn't_pay_the_Internet_bill_and_it's_been_cut_off.
    Lightning_strikes.
    Of_course_it_doesn't_work._We've_performed_a_software_upgrade.
    Change_your_language_to_Finnish.
    Fluorescent_lights_are_generating_negative_ions._If_turning_them_off_doesn't_work,_take_them_out_and_put_tin_foil_on_the_ends.
    High_nuclear_activity_in_your_area.
    What_office_are_you_in?_Oh,_that_one.__Did_you_know_that_your_building_was_built_over_the_universities_first_nuclear_research_site?_And_wow,_aren't_you_the_lucky_one,_your_office_is_right_over_where_the_core_is_buried!
    The_MGs_ran_out_of_gas.
    The_UPS_doesn't_have_a_battery_backup.
    Recursivity.__Call_back_if_it_happens_again.
    Someone_thought_The_Big_Red_Button_was_a_light_switch.
    The_mainframe_needs_to_rest.__It's_getting_old,_you_know.
    I'm_not_sure.__Try_calling_the_Internet's_head_office_--_it's_in_the_book.
    The_lines_are_all_busy_(busied_out,_that_is_--_why_let_them_in_to_begin_with?).
    Jan__9_16:41:27_huber_su:_'su_root'_succeeded_for_...._on_/dev/pts/1
    It's_those_computer_people_in_X_{city_of_world}.__They_keep_stuffing_things_up.
    A_star_wars_satellite_accidently_blew_up_the_WAN.
    Fatal_error_right_in_front_of_screen
    That_function_is_not_currently_supported,_but_Bill_Gates_assures_us_it_will_be_featured_in_the_next_upgrade.
    wrong_polarity_of_neutron_flow
    Lusers_learning_curve_appears_to_be_fractal
    We_had_to_turn_off_that_service_to_comply_with_the_CDA_Bill.
    Ionization_from_the_air-conditioning
    TCP/IP_UDP_alarm_threshold_is_set_too_low.
    Someone_is_broadcasting_pygmy_packets_and_the_router_doesn't_know_how_to_deal_with_them.
    The_new_frame_relay_network_hasn't_bedded_down_the_software_loop_transmitter_yet._
    Fanout_dropping_voltage_too_much,_try_cutting_some_of_those_little_traces
    Plate_voltage_too_low_on_demodulator_tube
    You_did_wha..._oh__dear_....
    CPU_needs_bearings_repacked
    Too_many_little_pins_on_CPU_confusing_it,_bend_back_and_forth_until_10-20%_are_neatly_removed._Do__not__leave_metal_bits_visible!
    _Rosin__core_solder?_But...
    Software_uses_US_measurements,_but_the_OS_is_in_metric...
    The_computer_fleetly,_mouse_and_all.
    Your_cat_tried_to_eat_the_mouse.
    The_Borg_tried_to_assimilate_your_system._Resistance_is_futile.
    It_must_have_been_the_lightning_storm_we_had_(yesterday)_(last_week)_(last_month)
    Due_to_Federal_Budget_problems_we_have_been_forced_to_cut_back_on_the_number_of_users_able_to_access_the_system_at_one_time._(namely_none_allowed....)
    Too_much_radiation_coming_from_the_soil.
    Unfortunately_we_have_run_out_of_bits/bytes/whatever._Don't_worry,_the_next_supply_will_be_coming_next_week.
    Program_load_too_heavy_for_processor_to_lift.
    Processes_running_slowly_due_to_weak_power_supply
    Our_ISP_is_having_{switching,routing,SMDS,frame_relay}_problems
    We've_run_out_of_licenses
    Interference_from_lunar_radiation
    Standing_room_only_on_the_bus.
    You_need_to_install_an_RTFM_interface.
    That_would_be_because_the_software_doesn't_work.
    That's_easy_to_fix,_but_I_can't_be_bothered.
    Someone's_tie_is_caught_in_the_printer,_and_if_anything_else_gets_printed,_he'll_be_in_it_too.
    We're_upgrading_/dev/null
    The_Usenet_news_is_out_of_date
    Our_POP_server_was_kidnapped_by_a_weasel.
    It's_stuck_in_the_Web.
    Your_modem_doesn't_speak_English.
    The_mouse_escaped.
    All_of_the_packets_are_empty.
    The_UPS_is_on_strike.
    Neutrino_overload_on_the_nameserver
    Melting_hard_drives
    Someone_has_messed_up_the_kernel_pointers
    The_kernel_license_has_expired
    Netscape_has_crashed
    The_cord_jumped_over_and_hit_the_power_switch.
    It_was_OK_before_you_touched_it.
    Bit_rot
    U.S._Postal_Service
    Your_Flux_Capacitor_has_gone_bad.
    The_Dilithium_Crystals_need_to_be_rotated.
    The_static_electricity_routing_is_acting_up...
    Traceroute_says_that_there_is_a_routing_problem_in_the_backbone.__It's_not_our_problem.
    The_co-locator_cannot_verify_the_frame-relay_gateway_to_the_ISDN_server.
    High_altitude_condensation_from_U.S.A.F_prototype_aircraft_has_contaminated_the_primary_subnet_mask._Turn_off_your_computer_for_9_days_to_avoid_damaging_it.
    Lawn_mower_blade_in_your_fan_need_sharpening
    Electrons_on_a_bender
    Telecommunications_is_upgrading._
    Telecommunications_is_downgrading.
    Telecommunications_is_downshifting.
    Hard_drive_sleeping._Let_it_wake_up_on_it's_own...
    Interference_between_the_keyboard_and_the_chair.
    The_CPU_has_shifted,_and_become_decentralized.
    Due_to_the_CDA,_we_no_longer_have_a_root_account.
    We_ran_out_of_dial_tone_and_we're_and_waiting_for_the_phone_company_to_deliver_another_bottle.
    You_must've_hit_the_wrong_any_key.
    PCMCIA_slave_driver
    The_Token_fell_out_of_the_ring._Call_us_when_you_find_it.
    The_hardware_bus_needs_a_new_token.
    Too_many_interrupts
    Not_enough_interrupts
    The_data_on_your_hard_drive_is_out_of_balance.
    Digital_Manipulator_exceeding_velocity_parameters
    appears_to_be_a_Slow/Narrow_SCSI-0_Interface_problem
    microelectronic_Riemannian_curved-space_fault_in_write-only_file_system
    fractal_radiation_jamming_the_backbone
    routing_problems_on_the_neural_net
    IRQ-problems_with_the_Un-Interruptible-Power-Supply
    CPU-angle_has_to_be_adjusted_because_of_vibrations_coming_from_the_nearby_road
    emissions_from_GSM-phones
    CD-ROM_server_needs_recalibration
    firewall_needs_cooling
    asynchronous_inode_failure
    transient_bus_protocol_violation
    incompatible_bit-registration_operators
    your_process_is_not_ISO_9000_compliant
    You_need_to_upgrade_your_VESA_local_bus_to_a_MasterCard_local_bus.
    The_recent_proliferation_of_Nuclear_Testing
    Elves_on_strike._(Why_do_they_call_EMAG_Elf_Magic)
    Internet_exceeded_Luser_level,_please_wait_until_a_luser_logs_off_before_attempting_to_log_back_on.
    Your_EMAIL_is_now_being_delivered_by_the_USPS.
    Your_computer_hasn't_been_returning_all_the_bits_it_gets_from_the_Internet.
    You've_been_infected_by_the_Telescoping_Hubble_virus.
    Scheduled_global_CPU_outage
    Your_Pentium_has_a_heating_problem_-_try_cooling_it_with_ice_cold_water.(Do_not_turn_off_your_computer,_you_do_not_want_to_cool_down_the_Pentium_Chip_while_he_isn't_working,_do_you?)
    Your_processor_has_processed_too_many_instructions.__Turn_it_off_immediately,_do_not_type_any_commands!!
    Your_packets_were_eaten_by_the_terminator
    Your_processor_does_not_develop_enough_heat.
    We_need_a_licensed_electrician_to_replace_the_light_bulbs_in_the_computer_room.
    The_POP_server_is_out_of_Coke
    Fiber_optics_caused_gas_main_leak
    Server_depressed,_needs_Prozac
    quantum_decoherence
    those_damn_raccoons!
    suboptimal_routing_experience
    A_plumber_is_needed,_the_network_drain_is_clogged
    50%_of_the_manual_is_in_.pdf_readme_files
    the_AA_battery_in_the_wallclock_sends_magnetic_interference
    the_xy_axis_in_the_trackball_is_coordinated_with_the_summer_solstice
    the_butane_lighter_causes_the_pincushioning
    old_inkjet_cartridges_emanate_barium-based_fumes
    manager_in_the_cable_duct
    We'll_fix_that_in_the_next_(upgrade,_update,_patch_release,_service_pack).
    HTTPD_Error_666_:_BOFH_was_here
    HTTPD_Error_4004_:_very_old_Intel_cpu_-_insufficient_processing_power
    The_ATM_board_has_run_out_of_10_pound_notes.__We_are_having_a_whip_round_to_refill_it,_care_to_contribute_?
    Network_failure_-__call_NBC
    Having_to_manually_track_the_satellite.
    Your/our_computer(s)_had_suffered_a_memory_leak,_and_we_are_waiting_for_them_to_be_topped_up.
    The_rubber_band_broke
    We're_on_Token_Ring,_and_it_looks_like_the_token_got_loose.
    Stray_Alpha_Particles_from_memory_packaging_caused_Hard_Memory_Error_on_Server.
    paradigm_shift...without_a_clutch
    PEBKAC_(Problem_Exists_Between_Keyboard_And_Chair)
    The_cables_are_not_the_same_length.
    Second-system_effect.
    Chewing_gum_on_/dev/sd3c
    Boredom_in_the_Kernel.
    the_daemons!_the_daemons!_the_terrible_daemons!
    I'd_love_to_help_you_--_it's_just_that_the_Boss_won't_let_me_near_the_computer._
    struck_by_the_Good_Times_virus
    YOU_HAVE_AN_I/O_ERROR_->_Incompetent_Operator_error
    Your_parity_check_is_overdrawn_and_you're_out_of_cache.
    Communist_revolutionaries_taking_over_the_server_room_and_demanding_all_the_computers_in_the_building_or_they_shoot_the_sysadmin._Poor_misguided_fools.
    Plasma_conduit_breach
    Out_of_cards_on_drive_D:
    Sand_fleas_eating_the_Internet_cables
    parallel_processors_running_perpendicular_today
    ATM_cell_has_no_roaming_feature_turned_on,_notebooks_can't_connect
    Webmasters_kidnapped_by_evil_cult.
    Failure_to_adjust_for_daylight_savings_time.
    Virus_transmitted_from_computer_to_sysadmins.
    Virus_due_to_computers_having_unsafe_sex.
    Incorrectly_configured_static_routes_on_the_corerouters.
    Forced_to_support_NT_servers;_sysadmins_quit.
    Suspicious_pointer_corrupted_virtual_machine
    It's_the_InterNIC's_fault.
    Root_name_servers_corrupted.
    Budget_cuts_forced_us_to_sell_all_the_power_cords_for_the_servers.
    Someone_hooked_the_twisted_pair_wires_into_the_answering_machine.
    Operators_killed_by_year_2000_bug_bite.
    We've_picked_COBOL_as_the_language_of_choice.
    Operators_killed_when_huge_stack_of_backup_tapes_fell_over.
    Robotic_tape_changer_mistook_operator's_tie_for_a_backup_tape.
    Someone_was_smoking_in_the_computer_room_and_set_off_the_halon_systems.
    Your_processor_has_taken_a_ride_to_Heaven's_Gate_on_the_UFO_behind_Hale-Bopp's_comet.
    it's_an_ID-10-T_error
    Dyslexics_retyping_hosts_file_on_servers
    The_Internet_is_being_scanned_for_viruses.
    Your_computer's_union_contract_is_set_to_expire_at_midnight.
    Bad_user_karma.
    /dev/clue_was_linked_to_/dev/null
    Increased_sunspot_activity.
    We_already_sent_around_a_notice_about_that.
    It's_union_rules._There's_nothing_we_can_do_about_it._Sorry.
    Interference_from_the_Van_Allen_Belt.
    Jupiter_is_aligned_with_Mars.
    Redundant_ACLs._
    Mail_server_hit_by_UniSpammer.
    T-1's_congested_due_to_porn_traffic_to_the_news_server.
    Data_for_intranet_got_routed_through_the_extranet_and_landed_on_the_internet.
    We_are_a_100%_Microsoft_Shop.
    We_are_Microsoft.__What_you_are_experiencing_is_not_a_problem;_it_is_an_undocumented_feature.
    Sales_staff_sold_a_product_we_don't_offer.
    Secretary_sent_chain_letter_to_all_5000_employees.
    Sysadmin_didn't_hear_pager_go_off_due_to_loud_music_from_bar-room_speakers.
    Sysadmin_accidentally_destroyed_pager_with_a_large_hammer.
    Sysadmins_unavailable_because_they_are_in_a_meeting_talking_about_why_they_are_unavailable_so_much.
    Bad_cafeteria_food_landed_all_the_sysadmins_in_the_hospital.
    Route_flapping_at_the_NAP.
    Computers_under_water_due_to_SYN_flooding.
    The_vulcan-death-grip_ping_has_been_applied.
    Electrical_conduits_in_machine_room_are_melting.
    Traffic_jam_on_the_Information_Superhighway.
    Radial_Telemetry_Infiltration
    Cow-tippers_tipped_a_cow_onto_the_server.
    tachyon_emissions_overloading_the_system
    Maintenance_window_broken
    We're_out_of_slots_on_the_server
    Computer_room_being_moved.__Our_systems_are_down_for_the_weekend.
    Sysadmins_busy_fighting_SPAM.
    Repeated_reboots_of_the_system_failed_to_solve_problem
    Feature_was_not_beta_tested
    Domain_controller_not_responding
    Someone_else_stole_your_IP_address,_call_the_Internet_detectives!
    It's_not_RFC-822_compliant.
    operation_failed_because:_there_is_no_message_for_this_error_(#1014)
    stop_bit_received
    internet_is_needed_to_catch_the_etherbunny
    network_down,_IP_packets_delivered_via_UPS
    Firmware_update_in_the_coffee_machine
    Temporal_anomaly
    Mouse_has_out-of-cheese-error
    Borg_implants_are_failing
    Borg_nanites_have_infested_the_server
    error:_one_bad_user_found_in_front_of_screen
    Please_state_the_nature_of_the_technical_emergency
    Internet_shut_down_due_to_maintenance
    Daemon_escaped_from_pentagram
    crop_circles_in_the_corn_shell
    sticky_bit_has_come_loose
    Hot_Java_has_gone_cold
    Cache_miss_-_please_take_better_aim_next_time
    Hash_table_has_woodworm
    Trojan_horse_ran_out_of_hay
    Zombie_processes_detected,_machine_is_haunted.
    overflow_error_in_/dev/null
    Browser's_cookie_is_corrupted_--_someone's_been_nibbling_on_it.
    Mailer-daemon_is_busy_burning_your_message_in_hell.
    According_to_Microsoft,_it's_by_design
    vi_needs_to_be_upgraded_to_vii
    greenpeace_free'd_the_mallocs
    Terrorists_crashed_an_airplane_into_the_server_room,_have_to_remove_/bin/laden._(rm_-rf_/bin/laden)
    astropneumatic_oscillations_in_the_water-cooling
    Somebody_ran_the_operating_system_through_a_spelling_checker.
    Rhythmic_variations_in_the_voltage_reaching_the_power_supply.
    Keyboard_Actuator_Failure.__Order_and_Replace.
    Packet_held_up_at_customs.
    Propagation_delay.
    High_line_impedance.
    Someone_set_us_up_the_bomb.
    Power_surges_on_the_Underground.
    Don't_worry;_it's_been_deprecated._The_new_one_is_worse.
    )
    
    excuse = excuses[rand(excuses.size)].gsub("_", " ")
     
    msg.speak("Your excuse is: #{excuse}")
  end
 

end


