#!/usr/bin/env ruby

# Run this script with the environment as the only argument. eg. ./script/bot development
BOT_ENVIRONMENT = ARGV.first
BOT_ROOT        = File.join(File.dirname(__FILE__), '..')

require File.join(BOT_ROOT, 'lib', 'bot')

bot.connect
bot.run